
# Changelog
# Author    Version       Date          Description
# SL        1.0.0         2022-10-04    Initial version, takeover from VG
# SL        1.1.0         2022-10-06    Changed to auto-generate metadata based on results' filenames
# SL        1.1.1         2023-01-20    Fixed gene selector. Updated about page
# SL        1.2.0         2023-01-24    Improved screen selector in bi-plots
# SL        1.3.0         2023-02-28    Changed so that plots do not update after each field selection
# SL        1.4.0         2023-04-26    Optimised loading times, enabled server-side lazy loading of genes list
# SL        1.5.0         2023-04-27    Further optimisations, reorganised code, mitigated against edge cases, rewrote rank plotting function

# TODO:
# Function-ise data loading into plots
# Enable ggplotly on rank plots
# Fix heatmap significance stars
# Add logging

# this template can be generated by writing 'shinyapp' and press tab

suppressPackageStartupMessages({
  library(tibble)
  library(ComplexHeatmap)
  library(tidyverse)
  library(shiny)
  library(ggplot2)
  library(visNetwork)
  library(heatmaply)
  library(shinydashboard)
  library(shinythemes)
  library(leaflet)
  library(shinyWidgets)
  library(ggpointdensity)
  library(igraph)
  library(Hmisc)
  library(foreach)
  library(data.table)
  library(R.utils)
})

########################################################### 
# Generate the metadata file
########################################################### 

# Look for drugZ result files. Interpret file path as: {Experimenter}/{Run}/result.{BackgroundRef}_{ConditionRef}-{BackgroundDiff}-{ConditionDiff}.tsv
result_meta <- tibble(file_location = list.files(path = ".", pattern = "^result\\..+\\.tsv.*$", recursive = T)) %>%
  mutate(ID = gsub("\\+", "\\|", file_location)) %>%
  mutate(Experimenter =   sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\1", ID),
         Run =            sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\2", ID),
         BackgroundRef =  sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\3", ID),
         ConditionRef =   sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\4", ID),
         BackgroundDiff = sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\5", ID),
         ConditionDiff =  sub("^.+?\\/(.+?)\\/(.+?)\\/result\\.(.+?)_(.+?)-(.+?)_(.+?)\\.tsv.*$", "\\6", ID))

result_meta <- result_meta %>% select(Experimenter, Run, BackgroundRef, ConditionRef, BackgroundDiff, ConditionDiff, file_location)

########################################################### 
# Screen comparisons
########################################################### 

# Tabulator - obtain all normZ scores and FDRs from a specified screen condition

tabulator_helper <- function(df, rownames, str) {
  df <- df %>% select(all_of(grep(str, names(df)))) %>% as.data.frame()
  names(df) <- sub(str, "", names(df))
  names(df) <- sub("^.+?\n(.+?)\n.+?$", "\\1", names(df))
  rownames(df) <- rownames
  return(df)
}

tabulator <- function(result_meta) {
  df <- foreach(i = 1:nrow(result_meta), .combine = "left_join") %do% {
    drugz_file_location <- result_meta$file_location[i]
    drugz <- fread(drugz_file_location)
    drugz_out <- drugz %>% transmute(GENE, normZ, fdr = pmin(fdr_synth, fdr_supp))
    names(drugz_out) <- c("GENE",
                          paste0(result_meta$Experimenter[i], " ", result_meta$Run[i], "\n", result_meta$BackgroundDiff[i], " ", result_meta$ConditionDiff[i], "\n", result_meta$BackgroundRef[i], " ", result_meta$ConditionRef[i], c("_normZ", "_fdr")))
    drugz_out
  }
  
  genes <- df$GENE
  df <- df %>% select(-GENE)
  
  df_normZ <- tabulator_helper(df, genes, "_normZ$")
  df_fdr <- tabulator_helper(df, genes, "_fdr$")
  
  return(list(normZ = df_normZ,
              fdr = df_fdr))
  
}

## TODO: ugly and hard-coded - remove and allow the user to specify their own comparison conditions

# # Etoposide
# df <- tabulator(result_meta %>%
#                   filter(BackgroundRef == "TP53") %>%
#                   filter(grepl("Etoposide", ConditionDiff)) %>%
#                   filter(grepl("DMSO", ConditionRef)))
# df_normz <- df$normZ
# df_fdr <- df$fdr
# 
# # Day25 essentialome
# ess <- tabulator(result_meta %>%
#                    filter(BackgroundDiff != "TP53") %>%
#                    filter(BackgroundRef == "TP53") %>%
#                    filter(grepl("DMSO", ConditionDiff)) %>%
#                    filter(grepl("DMSO", ConditionRef)))
# ess_normz <- ess$normZ
# ess_fdr <- ess$fdr
# 
# # Day10 fitness
# day10 <- tabulator(result_meta %>%
#                      filter(grepl("Day1.\\|NT", ConditionDiff)) %>%
#                      filter(BackgroundRef == "Plasmid") %>%
#                      filter(ConditionRef == "NT"))
# day10_normz <- day10$normZ
# day10_fdr <- day10$fdr
# 
# # Day25 fitness
# day25 <- tabulator(result_meta %>%
#                      filter(grepl("Day[23].\\|DMSO", ConditionDiff)) %>%
#                      filter(BackgroundRef == "Plasmid") %>%
#                      filter(ConditionRef == "NT"))
# day25_normz <- day25$normZ
# day25_fdr <- day25$fdr

# genes <- unique(c(rownames(df$normZ),
#                   rownames(ess$normZ),
#                   rownames(day10$normZ),
#                   rownames(day25$normz)))
# 
# genes <- grep("^NEG_CONTROL", genes, value = T, invert = T)

genes <- c(fread("data/GRCh38.genes.tsv", header = F)[[1]],
           fread("data/GRCm39.genes.tsv", header = F)[[1]])


########################################################### 
### SHINY UI ###
########################################################### 
ui <- bootstrapPage(
  tags$head(includeHTML("gtag.html")),
  navbarPage(theme = shinytheme("flatly"), collapsible = TRUE,
             HTML('<a style="text-decoration:none;cursor:default;color:#FFFFFF;" class="active" href="#">CRAVE</a>'), id="nav",
             windowTitle = "CRAVE",
             
             tabPanel("ABOUT",
                      tags$div(
                        h1("CRAVE: CRISPR-screen Rshiny app for visualisation and exploration"),tags$br(),
                        # "Our aim is to complement this study with several interactive features,including the ability to identify novel factors associated with Etoposide sensitivity and resistance.",
                        # tags$br(),
                        tags$br(),tags$h4("Welcome to CRAVE"), 
                        "CRAVE is being developed to unify all CRISPR screens done in the lab and to allow unconventional exploration of trends across genetic backgrounds and treatments.",tags$br(),
                        tags$br(),
                        "This app is under development. Some features will not work. Please report any bugs to the authors, contactable as below.",tags$br(),
                        tags$br(),
                        tags$h4("Authors"),
                        "Dr Simon Lam, Steve Jackson Lab, Cancer Research UK Cambridge Institute, University of Cambridge, UK",tags$br(),
                        tags$br(),tags$br(),
                        tags$h4("Contact"),
                        "sl681@cam.ac.uk",tags$br(),tags$br(),
                        tags$a(href='https://www.cam.ac.uk//', target="_blank", tags$img(src = "Colour logo RGB_DM.jpg", width = "361px", height = "75px")),
                        tags$a(href='https://www.stevejacksonlab.org/', target="_blank", tags$img(src = "new_lab_logo.png", width = "306px", height = "75px")),
                        tags$a(href='https://www.cruk.cam.ac.uk/', target="_blank", tags$img(src = "CRUK_CAMBRIDGE_I_Pos_CMYK.jpg", width = "341px", height = "75px"))
                      )
             ),
             
             
             
             # tabPanel("GENE QUERY",
             #          dashboardPage(
             #            dashboardHeader(disable = T),
             #            dashboardSidebar(
             #              span(tags$h4("Input Panel")),
             #              # Adjust the sidebar
             #              tags$style(".left-side, .main-sidebar {padding-top: 0px}"),
             #              selectizeInput('input_gene', 'Enter gene name', genes,multiple = T,selected = c("RNF4","ATM"),options = list(delimiter = " ", create = T)),
             #              hr(),
             #              checkboxInput(inputId = "check1", label = "Add SPJ Dan's Screen", value = FALSE),
             #              hr(),
             #              numericInput(inputId = "fdr",label = "FDR:",value = 0.2,min = 0, max = 1),
             #              hr(),
             #              sliderInput(inputId = "cor",label =  "Correlation:",min = 0, max = 1, value = 0.95, step = 0.05),
             #              width = 300
             #            ),
             #            
             #            dashboardBody(
             #              tabsetPanel(
             #                tabPanel(title="Heatmap",
             #                         fluidRow(
             #                           box(title="Etoposide hits",solidHeader = TRUE,width=6, status = "primary",plotOutput("heatmap1")),
             #                           box(title="Day10 v/s Library - Fitness Hits",solidHeader = TRUE,width=6,status = "primary",plotOutput("heatmap3"))),
             #                         fluidRow(tags$br()),
             #                         fluidRow(
             #                           box(title="Day25 v/s Library - Fitness Hits",solidHeader = TRUE,width=6, status = "primary",plotOutput("heatmap4")),
             #                           box(title="Day25-Differential Fitness Hits (KO-DMSO v/s WT-DMSO)",solidHeader = TRUE,width=6, status = "primary",plotOutput("heatmap2")))),
             #                tabPanel(title="Correlation",
             #                         fluidRow(
             #                           box(title="Etoposide Correlation table",solidHeader = TRUE,width=3, status = "primary",dataTableOutput("corr")),
             #                           box(title="Etoposide Correlation Network",solidHeader = TRUE,width=9, status = "primary",visNetworkOutput("network",height='800px'))
             #                         ))
             #                )
             #            )
             # )
             # ),
             # tabPanel("HEATMAPS",
             #          
             #          sidebarLayout(
             #            sidebarPanel(
             #              span(tags$i(h5("Input FDR to select hits across all screens.")), style="color:#045a8d"),
             #              numericInput(inputId = "fdr2",label = "FDR:",value = 0.05,min = 0, max = 1,step = 0.01),
             #              hr(),
             #              width = 2),
             #            
             #            mainPanel(
             #              tabsetPanel(
             #                tabPanel(title="Etoposide Hits",plotlyOutput("etop_interactive")),
             #                tabPanel(title="Day10 Fitness Hits",plotlyOutput("day10_ess")),
             #                tabPanel(title="Day25 Fitness Hits",plotlyOutput("day25_ess")),
             #                tabPanel(title="KO-DMSO v/s WT-DMSO Day25",plotlyOutput("diff_interactive")))
             #            )
             #          )
             # ),
             
             tabPanel("BI-PLOTS",
                      
                      sidebarLayout(
                        sidebarPanel(
                          
                          span(tags$i(h4("Select two conditions")), style="color:#045a8d"),
                          span(tags$i(h5("X-axis: Condition 1")), style="color:#045a8d"),
                          pickerInput("experimenter1", "Experimenter:", selected = NULL, choices = as.character(unique(result_meta$Experimenter)), options = pickerOptions(maxOptions = 1), multiple = T),
                          pickerInput("run1", "Run:", choices = NULL, multiple = F),
                          pickerInput("background1a", "Differential background:", choices = NULL, multiple = F),
                          pickerInput("condition1a", "Differential condition:", choices = NULL, multiple = F),
                          pickerInput("background1b", "Reference background:", choices = NULL, multiple = F),
                          pickerInput("condition1b", "Reference condition:", choices = NULL, multiple = F),
                          hr(),
                          span(tags$i(h5("Y-axis: Condition 2")), style="color:#045a8d"),
                          pickerInput("experimenter2", "Experimenter:", selected = NULL, choices = as.character(unique(result_meta$Experimenter)), options = pickerOptions(maxOptions = 1), multiple = T),
                          pickerInput("run2", "Run:", choices = NULL, multiple = F),
                          pickerInput("background2a", "Differential background:", choices = NULL, multiple = F),
                          pickerInput("condition2a", "Differential condition:", choices = NULL, multiple = F),
                          pickerInput("background2b", "Reference background:", choices = NULL, multiple = F),
                          pickerInput("condition2b", "Reference condition:", choices = NULL, multiple = F),
                          hr(),
                          span(tags$i(h5("Enter Gene name to highlight in Bi-plot")), style="color:#045a8d"),
                          selectizeInput('input_gene2', 'Gene name', NULL,multiple = T,options = list(delimiter = " ", create = T)),
                          hr(),
                          span(tags$i(h5("p-value cutoff for rank plots")), style="color:#045a8d"),
                          sliderInput('p_cutoff', 'p value cutoff', min = 0, max = 1, value = 0.1, step = 0.001),
                          hr(),
                          actionButton("biplotSubmit", "Submit"),
                          
                          width = 3
                        ),
                        
                        mainPanel(
                          tabsetPanel(
                            # tabPanel("Bi-plot", plotlyOutput("biplot")),
                            tabPanel("Bi-plot",
                                     fluidRow(
                                       box(title="Biplot",solidHeader = TRUE,height = 900, width = 9, status = "primary",plotOutput("biplot",brush = brushOpts(id = "plot1_brush"))),
                                       box(title="Selected Genes normZ scores",solidHeader = TRUE,width=3,height = 900, status = "primary",dataTableOutput("brush_info"))
                                     )
                                     # column(width = 8,plotOutput("biplot",brush = brushOpts(id = "plot1_brush"))),
                                     # column(width = 4,h4("Selected Genes normZ scores"),dataTableOutput("brush_info"))
                            ),
                            tabPanel("Condition-1 Rank Plot", plotOutput("rank_plot1")),
                            tabPanel("Condition-2 Rank Plot", plotOutput("rank_plot2"))
                          )
                        )
                      )
             )#,
             
             
             
             # tabPanel("CORRELATION NETWORK",
             #          div(class="outer",
             #              tags$head(includeCSS("styles.css")),
             #              visNetworkOutput("cor_net", width="100%", height="100%"),
             # 
             #              absolutePanel(id = "controls", class = "panel panel-default",
             #                            top = 75, left = 55, width = 250, fixed=TRUE,
             #                            draggable = TRUE, height = "auto",
             #                            span(tags$i(h5("Input FDR to select hits across all screens.")), style="color:#045a8d"),
             #                            sliderTextInput(inputId = "fdr3",label = "FDR:",selected = 0.05,choices = c(0.2,0.1,0.05),grid = TRUE),
             #                            hr(),
             #                            sliderInput(inputId = "cor2",label =  "Correlation:",min = 0.9, max = 1, value = 0.95, step = 0.05),
             #                            ),
             #                            
             #              absolutePanel(id = "controls", class = "panel panel-default",top = 400,
             #                                           left = 55, width = 250, fixed=TRUE,
             #                                          draggable = TRUE, height = "auto",
             #                            span(tags$i(h5("Color nodes based on etoposide screen score")), style="color:#045a8d"),
             #                            pickerInput("nodecolor1", "Color nodes by:",
             #                                        choices = c("Please select",names(df_normz)[!grepl("Dan\\|TP53", names(df_normz))]),
             #                                        selected = NULL,
             #                                        multiple = FALSE),
             #                            hr(),
             #                            selectizeInput("Focus", "Focus on node :", genes,multiple = F,selected = c("TDP2"),options = list(delimiter = " ", create = T))
             #               ),
             #         )
             # ),
             # 
             # tabPanel("PPI NETWORK",
             #          div(class="outer",
             #              tags$head(includeCSS("styles.css")),
             #              visNetworkOutput("ppi_net", width="100%", height="100%"),
             #              
             #              absolutePanel(id = "controls", class = "panel panel-default",
             #                            top = 75, left = 55, width = 250, fixed=TRUE,
             #                            draggable = TRUE, height = "auto",
             #                            span(tags$i(h5("Genes with DrugZ FDR <= 0.2 across all screens were selected as hits.")), style="color:#045a8d"),
             #                            hr(),
             #                            span(tags$i(h5("STRING PPI network was generated with confidence score > 0.4")), style="color:#045a8d"),
             #                            hr(),
             #                            span(tags$i(h5("Color nodes based on etoposide screen score")), style="color:#045a8d"),
             #                            pickerInput("nodecolor2", "Color nodes by:",
             #                                        choices = c("Please select",names(df_normz)[!grepl("Dan\\|TP53", names(df_normz))]),
             #                                        selected = NULL,
             #                                        multiple = FALSE),
             #                            hr(),
             #                            selectizeInput("Focus2", "Focus on node :", genes,multiple = F,selected = c("TDP2"),options = list(delimiter = " ", create = T))
             #                            )
             #              )
             #          )
  )
)



server <- function(input, output, session) {
  
  selectizeHelper <- function(observedCol, sel, updatedCol, inputId, session) {
    if(!any(is.null(sel))) {
      choices <- result_meta
      for(i in 1:length(sel)) {
        choices <- choices[choices[[observedCol[i]]]==sel[i],]
      }
      choices <- as.character(unique(choices[[updatedCol]])) # Upon the user picking option `sel` for field `observedCol`, return all possible `choices` for `updatedCol`
      updatePickerInput(session = session, inputId = inputId, choices = choices)                   # and update field with `inputID`
    }
  }
  
  updateSelectizeInput(session, 'input_gene2', choices = genes, server = TRUE, selected = c("RNF4","ATM"))
  
  observe({
    sel <- input$experimenter1
    selectizeHelper("Experimenter", sel, "Run", "run1", session)                  # When you pick an Experimenter, update the Run field
  })
  
  observe({
    sel <- c(input$experimenter1, input$run1)           # When you pick a Run, update Background Differentials
    selectizeHelper(c("Experimenter", "Run"), sel, "BackgroundDiff", "background1a", session)
    selectizeHelper(c("Experimenter", "Run"), sel, "BackgroundRef", "background1b", session)
  })
  
  observe({
    sel <- c(input$experimenter1, input$run1, input$background1a)
    selectizeHelper(c("Experimenter", "Run", "BackgroundDiff"), sel, "ConditionDiff", "condition1a", session) # When you pick Background Differential 1, update Condition Differential 1
  })
  
  observe({
    sel <- c(input$experimenter1, input$run1, input$background1b)
    selectizeHelper(c("Experimenter", "Run", "BackgroundRef"), sel, "ConditionRef", "condition1b", session) # When you pick Background Differential 2, update Condition Differential 2
  })
  
  observe({
    sel <- input$experimenter2
    selectizeHelper("Experimenter", sel, "Run", "run2", session)                  # When you pick an Experimenter, update the Run field
  })
  
  observe({
    sel <- c(input$experimenter2, input$run2)           # When you pick a Run, update Background Differentials
    selectizeHelper(c("Experimenter", "Run"), sel, "BackgroundDiff", "background2a", session)
    selectizeHelper(c("Experimenter", "Run"), sel, "BackgroundRef", "background2b", session)
  })
  
  observe({
    sel <- c(input$experimenter2, input$run2, input$background2a)
    selectizeHelper(c("Experimenter", "Run", "BackgroundDiff"), sel, "ConditionDiff", "condition2a", session) # When you pick Background Differential 1, update Condition Differential 1
  })
  
  observe({
    sel <- c(input$experimenter2, input$run2, input$background2b)
    selectizeHelper(c("Experimenter", "Run", "BackgroundRef"), sel, "ConditionRef", "condition2b", session) # When you pick Background Differential 2, update Condition Differential 2
  })
  

  
  # output$heatmap1 <- renderPlot({
  #   if(input$check1 == TRUE){
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene, ]
  #     hits_fdr <- df_fdr[rownames(df_fdr) %in% input$input_gene, ]
  #     hits_fdr <- as.data.frame(hits_fdr <= input$fdr)
  #   }else{
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene,  !grepl("Dan\\|TP53", names(df_normz))]
  #     hits_fdr <- df_fdr[rownames(df_fdr) %in% input$input_gene, !names(df_fdr) %in% "dan_etop" ]
  #     hits_fdr <- as.data.frame(hits_fdr <= input$fdr)
  #   }
  #   # print(t(hits_normz))
  #    hh <- ComplexHeatmap::Heatmap(t(hits_normz),
  #                                  clustering_distance_columns  = "pearson",
  #                                  clustering_distance_rows  = "pearson",
  #                                  column_names_side = "top",
  #                                 row_names_side = "left",
  #                                 name = "NormZ score",
  #                                 col = circlize::colorRamp2(c(min(df_normz,na.rm = T), 0, max(df_normz,na.rm = T)), c("red", "white", "blue")),
  #                                 heatmap_legend_param = list(color_bar = "continuous"),
  #                                 cell_fun = function(j, i, x, y, width, height, fill) {
  #                                   if(isTRUE(t(hits_fdr[j, i]) > 0))
  #                                     {grid.text("**", x, y,gp = gpar(fontsize=15, col="white"))}
  #                                   })
  #   draw(hh, merge_legend = TRUE)
  #   
  #   })
  # 
  # output$heatmap2 <- renderPlot({
  #   hits_normz <- ess_normz[rownames(ess_normz) %in% input$input_gene, ]
  #   hits_fdr <- ess_fdr[rownames(ess_fdr) %in% input$input_gene, ]
  #   hits_fdr <- as.data.frame(hits_fdr <= input$fdr)
  #   hh <- ComplexHeatmap::Heatmap(t(hits_normz),
  #                                 clustering_distance_columns  = "pearson",
  #                                 clustering_distance_rows  = "pearson",
  #                                 column_names_side = "top",
  #                                 row_names_side = "left",
  #                                 name = "NormZ score",
  #                                 col = circlize::colorRamp2(c(min(df_normz,na.rm = T), 0, max(df_normz,na.rm = T)), c("red", "white", "blue")),
  #                                 heatmap_legend_param = list(color_bar = "continuous"),
  #                                 cell_fun = function(j, i, x, y, width, height, fill) {
  #                                   if(isTRUE(t(hits_fdr[j, i]) > 0))
  #                                   {grid.text("**", x, y,gp = gpar(fontsize=15, col="white"))}
  #                                 })
  #   draw(hh, merge_legend = TRUE)
  # 
  # })
  # 
  # 
  # output$heatmap3 <- renderPlot({
  #   hits_normz <- day10_normz[rownames(day10_normz) %in% input$input_gene, ]
  #   hits_fdr <- day10_fdr[rownames(day10_fdr) %in% input$input_gene, ]
  #   hits_fdr <- as.data.frame(hits_fdr <= input$fdr)
  #   hh <- ComplexHeatmap::Heatmap(t(hits_normz),
  #                                 clustering_distance_columns  = "pearson",
  #                                 clustering_distance_rows  = "pearson",
  #                                 column_names_side = "top",
  #                                 row_names_side = "left",
  #                                 name = "NormZ score",
  #                                 col = circlize::colorRamp2(c(min(df_normz,na.rm = T), 0, max(df_normz,na.rm = T)), c("red", "white", "blue")),
  #                                 heatmap_legend_param = list(color_bar = "continuous"),
  #                                 cell_fun = function(j, i, x, y, width, height, fill) {
  #                                   if(isTRUE(t(hits_fdr[j, i]) > 0))
  #                                   {grid.text("**", x, y,gp = gpar(fontsize=15, col="white"))}
  #                                 })
  #   draw(hh, merge_legend = TRUE)
  #   
  # })
  # 
  # output$heatmap4 <- renderPlot({
  #   hits_normz <- day25_normz[rownames(day25_normz) %in% input$input_gene, ]
  #   hits_fdr <- day25_fdr[rownames(day25_fdr) %in% input$input_gene, ]
  #   hits_fdr <- as.data.frame(hits_fdr <= input$fdr)
  #   hh <- ComplexHeatmap::Heatmap(t(hits_normz),
  #                                 clustering_distance_columns  = "pearson",
  #                                 clustering_distance_rows  = "pearson",
  #                                 column_names_side = "top",
  #                                 row_names_side = "left",
  #                                 name = "NormZ score",
  #                                 col = circlize::colorRamp2(c(min(df_normz,na.rm = T), 0, max(df_normz,na.rm = T)), c("red", "white", "blue")),
  #                                 heatmap_legend_param = list(color_bar = "continuous"),
  #                                 cell_fun = function(j, i, x, y, width, height, fill) {
  #                                   if(isTRUE(t(hits_fdr[j, i]) > 0))
  #                                   {grid.text("**", x, y,gp = gpar(fontsize=15, col="white"))}
  #                                 })
  #   draw(hh, merge_legend = TRUE)
  #   
  # })
  # 
  # 
  # output$corr <- renderDataTable({
  #    if(input$check1 == TRUE){
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene, ]
  #     
  #     hits_fdr <- as.data.frame(df_fdr <= input$fdr)
  #     hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #     hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, ]
  # 
  #     cor_mat <- data.frame(cor(t(hits_fdr_genes_normz),t(hits_normz)))%>%
  #       rownames_to_column() %>%
  #       reshape2::melt()
  #     cor_mat <- cor_mat[cor_mat$value >= input$cor,]
  #     cor_mat <- cor_mat[cor_mat$rowname != as.character(cor_mat$variable),]
  #     cor_mat <- cor_mat[!duplicated(t(apply(cor_mat[,c(1,2)], 1, sort))),]
  #     
  #    }else{
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene, !grepl("Dan\\|TP53", names(df_normz))]
  # 
  #     hits_fdr <- as.data.frame(df_fdr <= input$fdr, )
  #     hits_fdr <- hits_fdr[,!grepl("Dan\\|TP53", names(hits_fdr))]
  #     hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #     hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, !grepl("Dan\\|TP53", names(df_normz))]
  #       
  #     cor_mat <- data.frame(cor(t(hits_fdr_genes_normz),t(hits_normz)))%>%
  #       rownames_to_column() %>%
  #       reshape2::melt()
  #     cor_mat <- cor_mat[cor_mat$value >= input$cor,]
  #     cor_mat <- cor_mat[cor_mat$rowname != as.character(cor_mat$variable),]
  #     cor_mat <- cor_mat[!duplicated(t(apply(cor_mat[,c(1,2)], 1, sort))),]
  #   }
  #   colnames(cor_mat) <- c("node1","node2","correlation")
  #   cor_mat
  # },options = list(pageLength = 10,dom = 'ltp',scrollX = TRUE))
  # 
  # output$network <- renderVisNetwork({
  #   if(input$check1 == TRUE){
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene, ]
  #     
  #     hits_fdr <- as.data.frame(df_fdr <= input$fdr)
  #     hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #     hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, ]
  #     
  #     cor_mat <- data.frame(cor(t(hits_fdr_genes_normz),t(hits_normz)))%>%
  #       rownames_to_column() %>%
  #       reshape2::melt()
  #     cor_mat <- cor_mat[cor_mat$value >= input$cor,]
  #     cor_mat <- cor_mat[cor_mat$rowname != as.character(cor_mat$variable),]
  #     cor_mat <- cor_mat[!duplicated(t(apply(cor_mat[,c(1,2)], 1, sort))),]
  #   }else{
  #     hits_normz <- df_normz[rownames(df_normz) %in% input$input_gene, !grepl("Dan\\|TP53", names(df_normz))]
  #     
  #     hits_fdr <- as.data.frame(df_fdr <= input$fdr, )
  #     hits_fdr <- hits_fdr[,!grepl("Dan\\|TP53", names(hits_fdr))]
  #     hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #     hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, !grepl("Dan\\|TP53", names(df_normz))]
  #     
  #     cor_mat <- data.frame(cor(t(hits_fdr_genes_normz),t(hits_normz)))%>%
  #       rownames_to_column() %>%
  #       reshape2::melt()
  #     cor_mat <- cor_mat[cor_mat$value >= input$cor,]
  #     cor_mat <- cor_mat[cor_mat$rowname != as.character(cor_mat$variable),]
  #     cor_mat <- cor_mat[!duplicated(t(apply(cor_mat[,c(1,2)], 1, sort))),]
  #   }
  #   
  #   nodes <- data.frame(id = unique(c(cor_mat$rowname,as.character(cor_mat$variable))),label = unique(c(cor_mat$rowname,as.character(cor_mat$variable))))
  #   edges <- data.frame(from = cor_mat$rowname, to = as.character(cor_mat$variable),value=cor_mat$value)
  #   
  #   visNetwork(nodes, edges) %>% 
  #     visNodes(shape = "circle") %>%
  #     visOptions(highlightNearest = list(enabled = TRUE, degree = 1,
  #                                        labelOnly = FALSE, hover = TRUE))
  # })
  # 
  # output$etop_interactive <- renderPlotly({
  #   hits_fdr <- as.data.frame(df_fdr <= input$fdr2)
  #   hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #   hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes,]
  #   heatmaply(t(hits_fdr_genes_normz),
  #             distfun = function(x) as.dist(1 - cor(t(x), method="pearson")),
  #             scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
  #               low = "red", 
  #               high = "blue", 
  #               midpoint = 0, 
  #               limits = c(min(hits_fdr_genes_normz,na.rm = T), max(hits_fdr_genes_normz,na.rm = T))))
  #   })
  # 
  # output$diff_interactive <- renderPlotly({
  #     hits_fdr <- as.data.frame(ess_fdr <= input$fdr2)
  #     hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #     hits_fdr_genes_normz <- ess_normz[rownames(ess_normz) %in% hits_fdr_genes,]
  #   heatmaply(t(hits_fdr_genes_normz),
  #             scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
  #               low = "red", 
  #               high = "blue", 
  #               midpoint = 0, 
  #               limits = c(min(hits_fdr_genes_normz,na.rm = T), max(hits_fdr_genes_normz,na.rm = T))))
  # })
  # 
  # output$day10_ess <- renderPlotly({
  #   hits_fdr <- as.data.frame(day10_fdr <= input$fdr2)
  #   hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #   hits_fdr_genes_normz <- day10_normz[rownames(day10_normz) %in% hits_fdr_genes,]
  #   heatmaply(t(hits_fdr_genes_normz),
  #             scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
  #               low = "red", 
  #               high = "blue", 
  #               midpoint = 0, 
  #               limits = c(min(hits_fdr_genes_normz,na.rm = T), max(hits_fdr_genes_normz,na.rm = T))))
  # })
  # 
  # output$day25_ess <- renderPlotly({
  #   hits_fdr <- as.data.frame(day25_fdr <= input$fdr2)
  #   hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #   hits_fdr_genes_normz <- day25_normz[rownames(day25_normz) %in% hits_fdr_genes,]
  #   heatmaply(t(hits_fdr_genes_normz),
  #             scale_fill_gradient_fun = ggplot2::scale_fill_gradient2(
  #               low = "red", 
  #               high = "blue", 
  #               midpoint = 0, 
  #               limits = c(min(hits_fdr_genes_normz,na.rm = T), max(hits_fdr_genes_normz,na.rm = T))))
  # })
  
  # Helper function to read DrugZ file from selection
  read_drugZ <- function(result_meta, experimenter, run, backgroundDiff, conditionDiff, backgroundRef, conditionRef) {
    if(!any(is.null(c(experimenter, run, backgroundDiff, conditionDiff, backgroundRef, conditionRef)))) {
    drugZ <- isolate(result_meta[(result_meta$Experimenter==experimenter &
                                     result_meta$Run==run &
                                     result_meta$BackgroundDiff==backgroundDiff &
                                     result_meta$ConditionDiff==conditionDiff &
                                     result_meta$BackgroundRef==backgroundRef &
                                     result_meta$ConditionRef==conditionRef),]$file_location)
    drugZ <- fread(paste0(getwd(), "/", drugZ))
    } else {
      drugZ <- tibble(GENE = "Please select", normZ = 0, fdr_synth = 0, fdr_supp = 0, rank_synth = 0)
    }
    return(drugZ)
  }
  
  # Read the selected DrugZ results files upon selection in the Biplots page
  init_df <- tibble(GENE = "", normZ = 0, fdr_synth = 0, fdr_supp = 0, rank_synth = 0) # Initialise with a dummy table when no file is selected yet
  init_diff <- "Please select"
  init_ref <- "Please select"
  
  plotdata <- reactiveValues(x_df = init_df,
                             y_df = init_df,
                             x_diff = init_diff,
                             x_ref = init_ref,
                             y_diff = init_diff,
                             y_ref = init_ref)
  observeEvent(input$biplotSubmit, { 
    plotdata$x_df <- read_drugZ(result_meta, input$experimenter1, input$run1, input$background1a, input$condition1a, input$background1b, input$condition1b)
    plotdata$y_df <- read_drugZ(result_meta, input$experimenter2, input$run2, input$background2a, input$condition2a, input$background2b, input$condition2b)
    plotdata$x_diff <- paste(input$background1a, input$condition1a)
    plotdata$x_ref <- paste(input$background1b, input$condition1b)
    plotdata$y_diff <- paste(input$background2a, input$condition2a)
    plotdata$y_ref <- paste(input$background2b, input$condition2b)} )
  
  # Render the biplot
  output$biplot <- renderPlot({
    input$biplotSubmit
    x_df <- plotdata$x_df %>% transmute(Gene = GENE, condition1 = normZ)
    y_df <- plotdata$y_df %>% transmute(Gene = GENE, condition2 = normZ)
    combined_data <- full_join(x_df, y_df, by = "Gene") %>% mutate(GOI = case_when(Gene %in% isolate(input$input_gene2) ~ T,
                                                                                   T ~ F))
    
    ggplot(combined_data, aes(x=condition1, y=condition2, label=Gene)) + 
      geom_pointdensity(adjust = 4,alpha=0.6) + 
      ggrepel::geom_label_repel(data = combined_data %>% filter(GOI), aes(x=condition1, y=condition2, label=Gene),
                                seed=99, alpha=0.9, size = 5, max.overlaps = Inf, colour="#1A85FF", parse = TRUE, force=3, segment.alpha=0.1, segment.color="black", segment.size=0.2) +
      geom_hline(yintercept = 0) +
      geom_vline(xintercept = 0) +
      geom_abline(slope = 1, linetype = "dotted") +
      scale_color_viridis_c() +
      scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
      scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
      xlab(paste(plotdata$x_ref, "→", plotdata$x_diff)) + 
      ylab(paste(plotdata$y_ref, "→", plotdata$y_diff)) +
      theme_classic() +
      theme(axis.text=element_text(size=14),axis.title=element_text(size=16,face="bold"),legend.position = "none")
  },height = 800)
  
  # Render the table, react with brush
  output$brush_info <- renderDataTable({
    input$biplotSubmit
    x_df <- plotdata$x_df %>% select(GENE, normZ)
    y_df <- plotdata$y_df %>% select(GENE, normZ)
    combined_data <- full_join(x_df, y_df, by = "GENE")
    names(combined_data) <- c("Gene","condition1","condition2")
    
    brushedPoints(combined_data, input$plot1_brush)
  },options = list(pageLength = 20,dom = 'fltip',scrollX = TRUE))
  
  # Rankplot plotter helper
  rankplotter <- function(my_df, my_ref, my_diff) {
    fdr_cut <- isolate(input$p_cutoff)
    dummy_df <- tibble(GENE = c(NA, NA, NA, NA), fdr_synth = c(0, 1, 1, 1), fdr_supp = c(1, 0, 1, 1), normZ = c(Inf, -Inf, Inf, Inf), rank_synth = c(Inf, -Inf, Inf, Inf)) # we need a dummy df to account for situations when not all Kinds are populated
    df <- bind_rows(dummy_df, my_df) %>%
      transmute(Gene = GENE, fdr = (pmin(fdr_synth, fdr_supp)), normZ, rank_synth) %>%
      mutate(GOI = case_when(Gene %in% isolate(input$input_gene2) ~ T,           # obtain manual GOIs
                             T ~ F),
             Kind = case_when(fdr <= fdr_cut & normZ < 0 ~ "Hypersensitising",   # obtain hits better than cutoff
                              fdr <= fdr_cut & normZ > 0 ~ "Suppressing",
                              GOI ~ "ZzzGOI",
                              T ~ NA),
             segment.colour = case_when(fdr <= fdr_cut & normZ < 0 ~ "#D41159",
                                        fdr <= fdr_cut & normZ > 0 ~ "#1A85FF",
                                        GOI ~ "#BBC714",
                                        T ~ NA),
             Top = case_when(!is.na(Kind) ~ T,                                   # prepare plotting order 
                             T ~ F),
             Label = case_when(!is.na(Kind) ~ Gene,
                               T ~ NA),
             Size = -log(fdr)) %>%
      arrange(Top)
    
    g <- ggplot(df, aes(x = rank_synth, y = normZ, fill = Kind, colour = Kind, alpha = Kind, label = Label, size = Size, segment.colour = segment.colour)) +
      ggrepel::geom_label_repel(seed=99, alpha=0.9, size = 3, max.overlaps = Inf, force=3, segment.alpha=0.2, segment.size=0.5, colour = "white",
                                xlim = c(1000, nrow(df)-1000), ylim = c(-Inf, Inf)) +
      geom_point(pch = 21) +
      scale_alpha_manual(values = c(0.5, 0.5, 0.5, 0.8)) +
      scale_colour_manual(values = c("#D41159", "#1A85FF", "#BBC714", "#AAAAAA")) +
      scale_fill_manual(values = c("#D41159", "#1A85FF", "#BBC714", "#AAAAAA")) +
      geom_hline(yintercept = 0, color = "grey") +
      theme_classic() +
      ggtitle(paste(my_ref, "→", my_diff)) +
      xlab("Rank") +
      ylab("normZ") +
      theme(legend.position = "none",
            panel.grid.major =element_blank(),
            panel.grid.minor = element_blank(),
            panel.background = element_rect(fill = "#FFFFFF", colour = "black",size = 1, linetype = "solid"),
            panel.border = element_rect(colour = "black", fill=NA, size=1),
            axis.text.x = element_text( color="black",size=18,angle=45,hjust=1),
            axis.text.y = element_text( color="black",size=18),
            axis.title = element_text( color="black",size=20,face="bold"),
            plot.title = element_text( size=20, face="bold", hjust=0.5 )) +
      scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
      scale_x_continuous(breaks = scales::pretty_breaks(n = 5),expand = c(0.1, 0.1))
    
    return(g)
  }
  
  # Render the x rankplot
  output$rank_plot1 <- renderPlot({
    input$biplotSubmit
    rankplotter(plotdata$x_df, plotdata$x_ref, plotdata$x_diff)    
  },height = 1200, width = 800)
  
  # Render the y rankplot, avoiding copy-pasting main loop
  output$rank_plot2 <- renderPlot({
    input$biplotSubmit
    rankplotter(plotdata$y_df, plotdata$y_ref, plotdata$y_diff)  
  },height = 1200, width = 800)
  
  # ++++++++++++++++++++++++++++
  # flattenCorrMatrix
  # ++++++++++++++++++++++++++++
  # cormat : matrix of the correlation coefficients
  # pmat : matrix of the correlation p-values
  flattenCorrMatrix <- function(cormat, pmat) {
    ut <- upper.tri(cormat)
    data.frame(
      row = rownames(cormat)[row(cormat)[ut]],
      column = rownames(cormat)[col(cormat)[ut]],
      cor  =(cormat)[ut],
      p = pmat[ut]
    )
  }
  
  
  # output$cor_net <- renderVisNetwork({
  #   
  #   hits_fdr <- as.data.frame(df_fdr <= input$fdr3, )
  #   hits_fdr <- hits_fdr[,!grepl("Dan\\|TP53", names(hits_fdr))]
  #   hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #   hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, !grepl("Dan\\|TP53", names(df_normz))]
  #     
  #   res2<-rcorr(as.matrix(t(hits_fdr_genes_normz)))
  #   # print(res2)
  #   cor_mat <- flattenCorrMatrix(res2$r, res2$P)
  #     
  #   cor_mat <- cor_mat[cor_mat$cor >= input$cor2,]
  #   nodes <- data.frame(id = unique(c(as.character(cor_mat$row),as.character(cor_mat$column))),
  #                         label = unique(c(as.character(cor_mat$row),as.character(cor_mat$column))),
  #                       color="#D2E5FF")
  #   edges <- data.frame(from = as.character(cor_mat$row), to = as.character(cor_mat$column),value=cor_mat$cor)
  #   
  #   
  #   # nodes$font.size <- sapply(as.character(nodes$id), function(x) nchar(x))
  # 
  # 
  #   visNetwork(nodes, edges) %>%
  #     visNodes(shape = "circle") %>%
  #     visOptions(highlightNearest = list(enabled = TRUE, degree = 1,
  #                                        labelOnly = FALSE, hover = TRUE))%>%
  #     visPhysics(enabled = T,solver= "forceAtlas2Based",forceAtlas2Based=list(gravitationalConstant= -100,centralGravity= 0.04,avoidOverlap=0.01),stabilization = list(enabled=F))%>%
  #     visLayout(randomSeed = 17)
  # })
  # 
  # observe({
  #   visNetworkProxy("cor_net") %>%
  #     visFocus(id = input$Focus, scale = 4)
  # })
  # 
  # 
  # 
  # observe({
  #   hits_fdr <- as.data.frame(df_fdr <= input$fdr3, )
  #   # hits_fdr <- as.data.frame(df_fdr1 <= 0.2, )
  #   hits_fdr <- hits_fdr[,!grepl("Dan\\|TP53", names(hits_fdr))]
  #   hits_fdr_genes <- row.names(hits_fdr[rowSums(hits_fdr) > 0,])
  #   #hits_fdr_genes_normz <- df_normz[rownames(df_normz) %in% hits_fdr_genes, !grepl("Dan\\|TP53", names(df_normz))]
  #   hits_fdr_genes_normz <- df_normz %>% filter(rownames(df_normz) %in% hits_fdr_genes) %>% select(!grep("Dan\\|TP53", names(df_normz)))
  #   
  #    
  #   library(Hmisc)
  #   res2<-rcorr(as.matrix(t(hits_fdr_genes_normz)))
  #   cor_mat <- flattenCorrMatrix(res2$r, res2$P)
  #   cor_mat <- cor_mat[cor_mat$cor >= input$cor2,]
  # 
  #   nodes <- data.frame(id = unique(c(as.character(cor_mat$row),as.character(cor_mat$column))),
  #                       label = unique(c(as.character(cor_mat$row),as.character(cor_mat$column))),
  #                       color="#D2E5FF")
  #   edges <- data.frame(from = as.character(cor_mat$row), to = as.character(cor_mat$column),value=cor_mat$cor)
  #   
  #   # print(input$nodecolor1)
  #   if(input$nodecolor1 != "Please select"){
  #   x_df <- hits_fdr_genes_normz[,input$nodecolor1,drop=F]
  #   x_df <- x_df[rownames(x_df) %in% nodes$id,,drop=F]
  #   # print(head(x_df))
  #   color.gradient <- function(x, colors=c("red","white","blue"), colsteps=100) {
  #     return( colorRampPalette(colors) (colsteps) [ findInterval(x, seq(min(df_normz,na.rm = T),max(df_normz,na.rm = T), length.out=colsteps)) ] )
  #   }
  #   
  #   pal <- colorNumeric("RdBu", domain = c(-max(abs(df_normz),na.rm = T),max(abs(df_normz),na.rm = T)))
  #   
  #   
  #   x_df$color_node <-  pal(x_df[,input$nodecolor1])
  #   x_df$label <- rownames(x_df)
  #   x_df <- x_df %>% rownames_to_column()
  #   colnames(x_df) <- c("id","normz","color","label")
  #   # print(x_df)
  #   visNetworkProxy("cor_net") %>%
  #     visUpdateNodes(nodes = x_df)}
  #   
  #   else{
  #     visNetworkProxy("cor_net") %>%
  #       visUpdateNodes(nodes = nodes)
  #   }
  # })
  
  
  # output$ppi_net <- renderVisNetwork({
  #   
  #   ppi_nodes <- data.table::fread("string_ppi_etoposide_hits_fdr_point2_confidence_point4_nodes.csv",sep=",",check.names = F) %>% as.data.frame()
  #   ppi_nodes <- ppi_nodes[,c("display name" ,"query term" )]
  #   
  #   ppi_edges <- data.table::fread("string_ppi_etoposide_hits_fdr_point2_confidence_point4_edges.csv",sep=",",check.names = F) %>% as.data.frame()
  #   edge1_node <- as.character(lapply(ppi_edges$name, function(x) strsplit(x," (pp) ",fixed=T)[[1]][[1]]))
  #   inds1 <- match(edge1_node, ppi_nodes$`display name`)
  #   edge1_node[!is.na(inds1)] <- ppi_nodes$`query term`[na.omit(inds1)]
  #   
  #   
  #   edge2_node <- as.character(lapply(ppi_edges$name, function(x) strsplit(x," (pp) ",fixed=T)[[1]][[2]]))
  #   inds2 <- match(edge2_node, ppi_nodes$`display name`)
  #   edge2_node[!is.na(inds2)] <- ppi_nodes$`query term`[na.omit(inds2)]
  #   
  #   
  #   nodes <- data.frame(id = as.character(ppi_nodes$`query term`),
  #                       label = as.character(ppi_nodes$`query term`),
  #                       shape='circle',
  #                       color="#D2E5FF")
  #   edges <- data.frame(from = as.character(edge1_node), to =as.character(edge2_node))
  #   
  #   graph <- graph.data.frame(edges,directed = F)
  #   degree_value <- degree(graph)
  #   degree_value[as.character(nodes$id)[!as.character(nodes$id) %in% as.character(names(degree(graph)))]] <- 0
  #   # print((degree_value[match(nodes$id, names(degree_value))]+1))
  #   nodes$font.size <- (degree_value[match(as.character(nodes$id), as.character(names(degree_value)))]+1)
  #   
  #   # betweeness_full <- as.data.frame(betweenness(graph_full,normalized = T))%>% rownames_to_column()
  #   
  #   visNetwork(nodes, edges) %>%
  #     visNodes(shape = "circle") %>%
  #     visOptions(highlightNearest = list(enabled = TRUE, degree = 1,
  #                                        labelOnly = FALSE, hover = TRUE))%>%
  #     # visIgraphLayout(type = "full",layout="layout.mds",randomSeed = 123)
  #   visPhysics(enabled = T,solver= "forceAtlas2Based",forceAtlas2Based=list(gravitationalConstant= -100,centralGravity= 0.04,avoidOverlap=0.01),stabilization = list(enabled=F))%>%
  #     visLayout(randomSeed = 17)
  # })
  
  # observe({
  #   visNetworkProxy("ppi_net") %>%
  #     visFocus(id = input$Focus2, scale = 4)
  # })
  
  # observe({
  #   ppi_nodes <- data.table::fread("string_ppi_etoposide_hits_fdr_point2_confidence_point4_nodes.csv",sep=",",check.names = F) %>% as.data.frame()
  #   ppi_nodes <- ppi_nodes[,c("display name" ,"query term" )]
  #   
  #   ppi_edges <- data.table::fread("string_ppi_etoposide_hits_fdr_point2_confidence_point4_edges.csv",sep=",",check.names = F) %>% as.data.frame()
  # 
  #   edge1_node <- as.character(lapply(ppi_edges$name, function(x) strsplit(x," (pp) ",fixed=T)[[1]][[1]]))
  #   inds1 <- match(edge1_node, ppi_nodes$`display name`)
  #   edge1_node[!is.na(inds1)] <- ppi_nodes$`query term`[na.omit(inds1)]
  #   
  #   
  #   edge2_node <- as.character(lapply(ppi_edges$name, function(x) strsplit(x," (pp) ",fixed=T)[[1]][[2]]))
  #   inds2 <- match(edge2_node, ppi_nodes$`display name`)
  #   edge2_node[!is.na(inds2)] <- ppi_nodes$`query term`[na.omit(inds2)]
  #   
  #   
  #   nodes <- data.frame(id = as.character(ppi_nodes$`query term`),
  #                       label = as.character(ppi_nodes$`query term`),
  #                       shape='circle',
  #                       color="#D2E5FF")
  #   edges <- data.frame(from = as.character(edge1_node), to =as.character(edge2_node))
  #   
  #   graph <- graph.data.frame(edges,directed = F)
  #   degree_value <- degree(graph)
  #   degree_value[as.character(nodes$id)[!as.character(nodes$id) %in% as.character(names(degree(graph)))]] <- 0
  #   # print((degree_value[match(nodes$id, names(degree_value))]+1))
  #   nodes$font.size <- (degree_value[match(as.character(nodes$id), as.character(names(degree_value)))]+1)
  #   
  #   # print(input$nodecolor2)
  #   
  #   if(input$nodecolor2 != "Please select"){
  #     x_df <- df_normz[,input$nodecolor2,drop=F]
  #     x_df <- x_df[rownames(x_df) %in% as.character(nodes$id),,drop=F]
  # 
  #   color.gradient <- function(x, colors=c("red","white","blue"), colsteps=100) {
  #     return( colorRampPalette(colors) (colsteps) [ findInterval(x, seq(min(df_normz,na.rm = T),max(df_normz,na.rm = T), length.out=colsteps)) ] )
  #   }
  # 
  #   pal <- colorNumeric("RdBu", domain = c(-max(abs(df_normz),na.rm = T),max(abs(df_normz),na.rm = T)))
  # 
  #   x_df$color_node <-  pal(x_df[,input$nodecolor2])
  #   x_df$label <- rownames(x_df)
  #   x_df <- x_df %>% rownames_to_column()
  #   colnames(x_df) <- c("id","normz","color","label")
  # 
  #   visNetworkProxy("ppi_net") %>%
  #     visUpdateNodes(nodes = x_df)
  #   }
  #   
  #   else{
  #     visNetworkProxy("ppi_net") %>%
  #       visUpdateNodes(nodes = nodes)
  #   }
  # })
}

shinyApp(ui, server)
